PROBLEM 1: NORMALIZATION

In [9]:
import numpy as np                               # Load NumPy for array operations
X = np.random.rand(5, 5)                         # Make a 5x5 array filled with random numbers
print("Original Array (X):\n", X)                # Show the unprocessed array

Original Array (X):
 [[0.83906145 0.93027198 0.30209647 0.8907496  0.5493837 ]
 [0.41909999 0.18595831 0.88855934 0.98747986 0.56262872]
 [0.80318505 0.7331002  0.54194218 0.88943946 0.95402703]
 [0.4059406  0.5170133  0.9488314  0.51866983 0.08111191]
 [0.90258918 0.3620065  0.75509363 0.19450064 0.98377142]]


In [10]:
mean = X.mean()                            # This computes the mean of X
std = X.std()                              # This computes the standard deviation of X
X_normalized = (X - mean) / std            # Formula for normalization

np.save("X_normalized.npy", X_normalized)  # Save the normalized array as "X_normalized.npy"

print("Original X:\n", X)
print("\nNormalized X:\n", X_normalized)

Original X:
 [[0.83906145 0.93027198 0.30209647 0.8907496  0.5493837 ]
 [0.41909999 0.18595831 0.88855934 0.98747986 0.56262872]
 [0.80318505 0.7331002  0.54194218 0.88943946 0.95402703]
 [0.4059406  0.5170133  0.9488314  0.51866983 0.08111191]
 [0.90258918 0.3620065  0.75509363 0.19450064 0.98377142]]

Normalized X:
 [[ 0.69606938  1.02468494 -1.23852158  0.88229271 -0.34758894]
 [-0.81697835 -1.65694707  0.87440159  1.23079494 -0.29986944]
 [ 0.56681297  0.31430948 -0.37439944  0.87757253  1.11027025]
 [-0.86438933 -0.46421384  1.09155131 -0.45824566 -2.03469035]
 [ 0.92494866 -1.02267624  0.39354799 -1.62617058  1.21743408]]


PROBLEM 2: NUMBERS DIVISIBLE BY 3

In [11]:
import numpy as np                              # Import the NumPy library
A = np.arange(1, 101) ** 2                      # Generate squares of numbers 1 through 100

A = A.reshape(10, 10)                           # Arrange into a 10x10 array
print("10x10 Array of Squares:\n", A)           # Display the reshaped array

10x10 Array of Squares:
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]


In [12]:
div_by_3 = A[A % 3 == 0]                        # Extract elements divisible by 3

np.save("div_by_3.npy", div_by_3)               # Store results in a .npy file

print("\nNumbers divisible by 3:\n", div_by_3)  # Print extracted elements


Numbers divisible by 3:
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
